### ISSUE TITLE
wget unable to use https based proxies - swap to curl?

### ISSUE THREAD

**Issue by wrightlaw** [DBezemer/rpm-haproxy#32] opened 2020-10-06 16:24 UTC
Would it be possible to swap to using curl rather than wget for downloads? Reason being that wget (or at least the version that's default on CentOS 7 boxes) does not seem to be capable of using https based proxy servers (i.e. http_proxy=https://whatever:3128 / https_proxy=https://whatever:3128

If this would be acceptable, I'm more than happy to submit a pull request with what I'm using locally!

Thanks for the excellent work!

**Comment by DBezemer** [comment] 2020-11-03 10:14
Thanks for the pull, I'll test and merge if it works as intended. No personal preference between curl or wget.
You can use wget with corporate proxies as well, either system wide with /etc/wgetrc or ~/.wgetrc
```
use_proxy=yes
http_proxy=127.0.0.1:8080
https_proxy=127.0.0.1:8080
```

**Comment by wrightlaw** [comment] 2020-11-03 13:51
> Thanks for the pull, I'll test and merge if it works as intended. No personal preference between curl or wget.
> You can use wget with corporate proxies as well, either system wide with /etc/wgetrc or ~/.wgetrc
> 
> ```
> use_proxy=yes
> http_proxy=127.0.0.1:8080
> https_proxy=127.0.0.1:8080
> ```

Awesome, thanks! Issue we had with wget was that yes we could use it with http based proxies, however our proxies mandate access via https (to the proxy itself) which curl copes with, but wget fails on with an error.

**Comment by DBezemer** [comment] 2021-04-11 22:22
finally got around to verifying, merged into main branch

**Closed as completed** 2021-04-11 22:31 UTC
